// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/slickgrid/slick.rowselectionmodel.d.ts
declare namespace Slick {
    class RowSelectionModel<T extends SlickData, E> extends SelectionModel<T, E> {
        constructor(options?:{selectActiveRow:boolean;});

        getSelectedRows():number[];

        setSelectedRows(rows:number[]):void;

        getSelectedRanges():number[];

        setSelectedRanges(ranges:number[]):void;
    }
}
